### ISSUE TITLE
Refatorar sistema de votação de posts

### ISSUE THREAD

**Issue by joaobenthin** [muvesoft/knowshare-front#5]
Pessoa só poderá votar 1 vez por post, escolhendo se gostou ou não

**Comment by vinioo** [comment]
Acredito que os votos podem ser visiveis, porem o sistema não pode reordenar os itens da forma que está hoje, pois com muitos usuários ao mesmo tempo seria um problema. 
Uma solução interessante seria manter o sistema de votos mas ordenar pela % de relevância somente ao recarregar a página

**Comment by joaobenthin** [comment]
Ok, irei desenvolver e abrirei uma PR

**Comment by vinioo** [comment]
vc é o cara
